import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import { GameProvider } from "./context/gameContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rock Paper Scissors Game",
  description: "Generated by Mehmet Akif AKKUS-Osman Yusuf AKKUS",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " flex py-10 px-8 min-h-screen flex-col bg-gradient-radial from-gradient-radial-start to-gradient-radial-end items-center gap-14"
        }
      >
        <GameProvider>
          <Header />
          {children}
        </GameProvider>
      </body>
    </html>
  );
}
